// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    return function(code) {
      var parser, result;
      parser = require('src/parser');
      result = parser(code);
      console.log('result:', result);
      return 'return from generator';
    };
  });

}).call(this);

/*
//@ sourceMappingURL=generator.map
*/
