// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    var code, generator, html;
    generator = require('src/generator');
    code = require('text!cirru/cirru.cirru');
    html = generator(code);
    return document.querySelector('#container').innerHTML = html;
  });

}).call(this);

/*
//@ sourceMappingURL=render.map
*/
