// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    var code, generator;
    generator = require('src/generator');
    code = require('text!cirru/cirru.cirru');
    return generator(code);
  });

}).call(this);

/*
//@ sourceMappingURL=render.map
*/
