name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: yarn
        registry-url: https://registry.npmjs.org/

    - name: "compiles to js"
      run: >
        yarn && yarn compile && yarn vite build --base=./

    - name: publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
