name: Upload

on:
  push:
    branches:
      - master
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'yarn'

    - name: "compiles to js"
      run: >
        yarn && yarn compile && yarn vite build --base=./
        && cp -r examples dist/

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
